From f1d741da10de78485a645b28a1dc9e09bfc6fdf4 Mon Sep 17 00:00:00 2001
From: Mathieu Desnoyers <mathieu.desnoyers@polymtl.ca>
Date: Thu, 30 Oct 2008 23:26:56 -0400
Subject: [PATCH] lttng-tracer-return-error-for-trace-start-uncreated-trace

Hi Mathieu,

I find ltt_trace_start don't return error when trace_name is not exist.
So, when we use lttctl -s to start no-exist channel, it will not print
 any errormsg:
  # ls /mnt/debugfs/ltt/
  # lttctl -n zltest -s
  Linux Trace Toolkit Trace Control 0.54-10102008

  Controlling trace : zltest

  # ls /mnt/debugfs/ltt/
  #

It can be fixed by following patch, I tested patched kernel with following command:
  # ls /mnt/debugfs/ltt/
  # lttctl -n zltest -s
  Linux Trace Toolkit Trace Control 0.54-10102008

  Controlling trace : zltest

  Start Trace Error: No such file or directory
  #

Signed-off-by: Zhaolei <zhaolei@cn.fujitsu.com>
---
 ltt/ltt-tracer.c |    4 ++--
 1 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/ltt/ltt-tracer.c b/ltt/ltt-tracer.c
index 68bfa35..0364fdf 100644
--- a/ltt/ltt-tracer.c
+++ b/ltt/ltt-tracer.c
@@ -617,9 +617,9 @@ static int ltt_trace_start(const char *trace_name)
 	ltt_lock_traces();
 
 	trace = _ltt_trace_find(trace_name);
-	if (trace == NULL)
-		goto no_trace;
 	err = _ltt_trace_start(trace);
+	if (err)
+		goto no_trace;
 
 	ltt_unlock_traces();
 
-- 
1.5.5.1

